language: node_js
node_js:
  - v10.23.2
  - v12.20.1
  - v14.15.4
sudo: false
before_install:
  - npm install -g npm
install:
  - npm install
script:
  - npm run test
  - npm run coverage
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: ilya@doublenot.co
  api_key:
    secure: Vx2Bra3A5PKf07N3h2ncAXycM2TF1JoDgJJb2OAVBkY6thX4N5D5wEoDSfX5wW4ctshQ8PAN6A3NEP13dWXHHfIRHfQPPc6bWJlzRPeyzp1wheVc37LqKkpGp6YVs6NKxOfsEYhVkHhiaWhOVbpDkw4e9XNLJmKi2CPs6vb1Og0B4SFWtD2WJIKyBWignbePsDnFvPg3V6V6eePrP2+kfSMcOfwvX+HCi4HflnhRqhDMVre9YnUdq43b1GEzgd19MujSXl5Za/SCcHuZ0EH6E4QFJnBC9DwDupRed8dKsn2nJ+wOac+KQdAuWRm/9OlviiHWtHz2RXR5H3hTZ/bpHMvwOBTTV5FuMcb1SlbvLCQN63OmLEktCo5PKhpQjnzRfrqDUZCYJrfgg3jajg/A7qkoWKi0EYYirGp+yoClNFx5v4m7BRC45WZ+gMhpLtk7Z9irqC1++JkTQH89Mn7AYhzvgC/KywFsktPCzsxqhjX+64p35Z8ajHnOeVUMrKAR5eqLzP2to00YOeXlKhtoTjuukAX5Vknr26BrzfKBn4UccrMRcDR4eTeGvFk5Aobt6O3Mfg1EYCCRM3nUV5w52HloBEw5hVpn/a9jtXgoR79l06RkG+g0K7qKxCCGHzEbKKnwPJL6TpD32CLVB8rxfmq0nkhi46s7B9ijZN/7rm8=
  on:
    tags: true
    repo: doublenot/refs
